// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Prefer Windows Auth when USE_TRUSTED_CONNECTION is enabled; otherwise SQL auth.
 */
function resolveMigrateUrl(): string {
  const useTrusted =
    process.env.USE_TRUSTED_CONNECTION === "true" ||
    process.env.USE_TRUSTED_CONNECTION === "1";

  const url = useTrusted
    ? process.env.DATABASE_URL_TRUSTED
    : process.env.DATABASE_URL;

  if (!url) {
    throw new Error(
      useTrusted
        ? "DATABASE_URL_TRUSTED is required when USE_TRUSTED_CONNECTION=true"
        : "DATABASE_URL is required when USE_TRUSTED_CONNECTION is not true"
    );
  }

  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolveMigrateUrl(),
  },
});
